language: node_js

node_js:
  - "7"
  - "8"

sudo: false

dist: trusty

os:
  - linux
  - osx

env:
  global:
    - secure: iYfhZV5+0bS388n9bX26V27hBqoMLmX5zvoIIRUhPXM7X148oa2IvZxkSaURRYMlVl9KkKab9/ol2SK6yZZL+U33XGIxP6H5bFlophNRo4emUVpnRlw1B7lOgzY11crYE4/iMMtdYN635thkbwIA4d0Ny9yiGOle6RWoDczNeWDFLFp3hhsa64Es30BVOABXEMw52Z02WqlsO9cdjyGVOzbP23SClzjY+O1zkH7UGxcaUcpoZMYliumP9FaeUOsEKiYJd4JX1oW5SZXjj1lubUM/rzhcNEd2S3kJ1teDIfnxHz/WwsrY9MeIIAByU8PIpjJoIxz0YPEUfwgIUeL8fQcSeWShNEE+oaw3jkVMq8mYpQgHeRB78W2e02r0e8xftJR0z37GRtZwtaWL19viGqCQCemC8wRp5AL3dTKqkGgdrngG63BaWuhKk4ujiAQBo1HiOn73qyOAEX8ITG+rU7Lvng3d+G7j6m4+b53de9jcU0Z2YaZO7nbqZcTUrYnaP6STucLRWeNdwVzcGuTCm3f0dkvxa95HJMxXlf4Sle8pVko9pNqq7PeuqR8uSD51MkVWdgbGDVC0RPjEoCqoIcoVDQ2ZdTQrgWFn4gvDKigRULw9aV1WiBhjSug0LTL5Prr/cYvS/VUzPeHkZOErqD16qYQyM3/l6EMnm6qrrZ4=
    - secure: Q4ChW8MN7/YU+IhSMHAGUaVkes7eK4u4kpsNxYU352uIaSHgFpc+hUq6q9mU53YO7Kvw+LQphK9t9dgFGL4HXI/miEfiatKIe45bBVhdCxsmV6s4JenhWMV/OmbPRZuiE7cfLYU2+ASIEoCPZ886vXg9ZXafmm9iSvviQuYupJ2bw92aFSZo9GoAHvL3Q2e0D4Y9WWc08E45bQWRUXxoFXHPAzd8xgCUs6zR60C4zPsq65nz1fGSxRM5V73y9GJk5S4iruailarYYJgqPHNWjfgLwNAM1msJPLC04ah2G1WUAlqP1MdGK63jpsQYXgpJpGyEhwuus+k7f/l4bE8/PLPzZtv/BVEljCluv81kDxz++MoxH2aStGkN2zYam92TEYe4rwMboKMEDvz2pMVVcUotjKt1t883k6x3zANyMrVO2DzouIvWun6gNz9m1hazkZslSuzDVG0p9g36YtOzKpEaGeyomtn6XCfJ3NL7PFXiy39M/gXyyJRENh/odwXU78otS33PH3qfh4Ia3nOFDC3GzxWkTDzz8MixfQNSwiIDGFu9r38Tsfz/c7ISTipaHFC/6d17PFnb74erTA8/4XYkeMPYP8MzIXbcT+TUasif4zq8yFn5e1k9T30Tn61ANHgsnFds4q+b1rZx1UQah9XR1bkQ2t5wtHc7dLfoSTI=

addons:
  apt:
    packages:
    - graphviz

cache:
  apt: true
  yarn: true
  bundler: true
  cargo: true
  directories:
  - node_modules
  - "$HOME/.cargo"
  - "$HOME/.nvm"
  - "$HOME/.rustup"

jobs:
  include:
    - stage: docker push
      # if: type IN (push)
      if: branch IN (master, release)
      sudo: required
      services:
        - docker
      os: "linux"
      script: skip
      deploy:
        provider: script
        script: bash scripts/deploy-docker.sh

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -OL https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unzip protoc-3.5.1-linux-x86_64.zip
    -d $HOME/protoc3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -OL https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-osx-x86_64.zip;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unzip protoc-3.5.1-osx-x86_64.zip -d $HOME/protoc3;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:kzemek/boost;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost1.58-dev;
    fi
  - export PATH=$HOME/protoc3/bin:$PATH
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PYTHON=python2.7
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup update
  - rustc -Vv
  - cargo -V
  - rustup default nightly
  - rustup component add rust-src
  - export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src
  - export RUST_BACKTRACE=1
  - mkdir logs

script:
  - yarn
  - yarn run dist

notifications:
  email:
  - aj@blockcollider.org
  - ak@blockcollider.org
  - pm@blockcollider.org
  - tk@blockcollider.org
